name: release to quay.io
'on':
  push:
    tags:
    - v*
jobs:
  push-image:
    name: push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.17'
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: validate tag
      id: validate_tag
      run: ./validate-tag.sh
    - name: output
      run: echo "The valid tag was ${{ steps.validate_tag.outputs.tag }}"
